config/routes.rb
Rails.application.routes.draw do
  resources :listings, except: [:index]

  resources :categories, only: [:show]

  root 'listings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listings, dependent: :nullify
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :category
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= render partial: 'listings/list', locals: {
    listings: @category.listings } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thinklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'thinkful.png', class: 'logo' %>
          Thinklist
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'All', root_path %>
                </li>
                <% Category.order('name ASC').each do |category| %>
                <li>
                  <%= link_to category.name, category %>
                </li>
                <% end %>
              </ul>
            </li>
            <li>
              <%= link_to 'New', new_listing_path %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</p>
      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {
      include_blank: "Please select..." }, { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.number_field :price, class: 'form-control', step: 'any', min: 0 %>
    </div>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
<% end %>

app/views/listings/_list.html.erb
<% if listings.empty? %>
  No listings to display! Go <%= link_to 'create one', new_listing_path %>.
<% else %>
  <table class="table table-striped">
    <tbody>
      <% @listings.each do |listing| %>
        <tr>
          <td><%= link_to listing.title, listing %></td>
          <td class="text-right">
            <% if listing.price %>
              <%= number_to_currency(listing.price) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<h1>Listings</h1>
<%= render partial: 'list', locals: { listings: @listings } %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

app/views/listings/show.html.erb
<p>
  <strong>Category:</strong>
  <% if @listing.category %>
    <%= link_to @listing.category.name, @listing.category %>
  <% else %>
    none
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<% if @listing.price %>
  <p>
    <strong>Price:</strong>
    <%= number_to_currency(@listing.price) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-default' %>
<%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>